### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by victorpreuss** [cjheath/AD9959#3]
hey, i was using your code as reference to use an stm32 microcontroller to control the ad9959 and was wondering if you shouldn't have used a pre-increment (--len) or used a 'greater than' (>) signal at line 420:

https://github.com/cjheath/AD9959/blob/251e54b3fc76f47b91cd0bd36e7062c2c3802c0f/AD9959.h#L420

this while loop will run an extra time (5 times if len=4)

**Comment by cjheath** [comment]
Many thanks. Fixed in #5303961. I tested this as well as possible without access to the actual hardware.

**Comment by victorpreuss** [comment]
i appreciate your effort, it helped me a lot!

**Comment by cjheath** [comment]
Please let me know if you have success, and also if you find further problems. I hope to be able to use this code in anger this year :)
