### ISSUE TITLE
use of sweep...( )

### ISSUE THREAD

**Issue by chunsik79** [cjheath/AD9959#5]
@cjheath 

After a long time of trial and error, I was able to get the the sine wave generated from AD9959 evaluation board using ArduinoUNO. Thank you for your help.    

Here is the evaluation board, arduino uno, and two level shifters 

![board setting](https://user-images.githubusercontent.com/30134870/69284398-64fb7f80-0ba3-11ea-936b-eca43ffd4b6a.jpg)

Below is an oscilloscope output plot.

![sine wave from AD9958](https://user-images.githubusercontent.com/30134870/69284410-6cbb2400-0ba3-11ea-9745-00da98e5a536.png)

However, when I try "Sweeps", it doesn't work yet. Is there something not right in my code? I attached my current code at the end of this message. 

Here is warning messages from my Arduino IDE.

...\libraries\AD9959/AD9959.h:224:32: warning: invalid conversion from 'long int' to 'AD9959<10, 7, 2, 10000000, 100000, 13, 12, 11>::CFR_Bits' [-fpermissive]

...\libraries\AD9959/AD9959.h: In instantiation of 'void AD9959<ResetPin, ChipEnablePin, UpdatePin, reference_freq, SPIRate, SPIClkPin, SPIMISOPin, SPIMOSIPin>::sweepAmplitude(AD9959<ResetPin, ChipEnablePin, UpdatePin, reference_freq, SPIRate, SPIClkPin, SPIMISOPin, SPIMOSIPin>::ChannelNum, uint16_t, bool) [with unsigned char ResetPin = 10; unsigned char ChipEnablePin = 7; unsigned char UpdatePin = 2; long unsigned int reference_freq = 10000000; long int SPIRate = 100000; unsigned char SPIClkPin = 13; unsigned char SPIMISOPin = 12; unsigned char SPIMOSIPin = 11; uint16_t = unsigned int]':

...\transmitter_modulation2.ino:38:43:   required from here

...\libraries\AD9959/AD9959.h:360:44: warning: left shift count >= width of type [-Wshift-count-overflow]

     write(CW1, ((uint32_t)amplitude) * (0x1<<(32-10)));

                                        ~~~~^~~~~~~~~~


Below is the full code that worked to generate single tone signal and the "Sweeps" that I am trying. 




`#include "AD9959.h"

class MyAD9959 : public AD9959<
  10,    // ResetPin
  7,    // ChipEnablePin
  2,   // UpdatePin
  10000000, // (reference_frequency)
  100000,//
  13,//
  12,//
  11//
  // SPIRate, SPIClkPin, SPIMISOPin, SPIMOSIPin
> {};

void setup() { 
pinMode(6, OUTPUT); // 

//SPI.begin(); // start the SPI library:

MyAD9959 dds;
//delay(1);

dds.setClock(20, 0);

uint32_t  delta;
delta = dds.frequencyDelta(5000);

delta=dds.frequencyDelta(455000);
dds.setFrequency(MyAD9959::Channel2, 5000000UL);  // shorthand for:
dds.setDelta(MyAD9959::Channel2, dds.frequencyDelta(5000000UL));  // 7.14MHz
dds.setAmplitude(MyAD9959::Channel2, 1023);   // Maximum amplitude value
dds.setPhase(MyAD9959::Channel2, 16383);    // Maximum phase value (same as -1)
dds.update();

dds.sweepFrequency(MyAD9959::Channel2, 8000000);  // Target frequency
dds.sweepDelta(MyAD9959::Channel2, delta, false);// Target frequency delta
dds.sweepAmplitude(MyAD9959::Channel2, 512); // Target amplitude (half)
//dds.sweepPhase(MyAD9959::Channel2, 8192);  // Target phase (180 degrees)
dds.sweepRates(MyAD9959::Channel2, 100, 125, 1000, 250);

digitalWrite(6, HIGH);
delay(1000);

digitalWrite(6, LOW);
delay(1000);

}

void loop() {
 digitalWrite(6, HIGH);
    delay(1000);

    digitalWrite(6, LOW);
    delay(1000);

}`

**Comment by cjheath** [comment]
At this line https://github.com/cjheath/AD9959/blob/eefac4c1d0b72d24db106bbf63fd2f17cb6fc5b9/AD9959.h#L360
the "0x1" is shifted left by 22 bits and multiplied by 512 (your amplitude value), resulting in a value that fits in uint32_t but not in int32_t. I thought that the result should be unsigned, but the compiler disagrees, and I'm not up with the latest standards.

Try changing that line to this:

    write(CW1, ((uint32_t)amplitude) * ((uint32_t)0x1<<(32-10)));

or lowering the 512 to 511 in your call so the result fits in a signed 32-bit integer (though it should work up to 1023, the maximum amplitude value).

Beyond that, you're on your own. I haven't tested amplitude modulation, and anyway, this is a C++ language question, not a question about the library.

**Comment by cjheath** [comment]
By the way, I would try to get frequency sweeps happening first. There's none of the auto ramp-up/down complexity that amplitude ramping has. See the data sheet p28 "OUTPUT AMPLITUDE CONTROL MODE" to understand more. It's complicated and I might not have got everything right. After configuring the device, you also need the profile pins set correctly to make it ramp up or down.
