### ISSUE TITLE
Bug with reading register?

### ISSUE THREAD

**Issue by b-d-doyle** [cjheath/AD9959#8]
Hi, to get `read(reg)` to work for me, I had to make a small change to `write(reg,value)`.

To read register `reg`, you write `0x80|reg`. But this bit makes the write function always think the register's length is 4.

https://github.com/cjheath/AD9959/blob/eefac4c1d0b72d24db106bbf63fd2f17cb6fc5b9/AD9959.h#L448

I got it to work for me by changing line 448 to:
`int         len = (reg&0x1F) < sizeof(register_length) ? register_length[reg&0x1F] : 4;`

**Comment by cjheath** [comment]
Many thanks. Obviously read() has not had much use! I pushed a slightly more cautious version of this change.

**Comment by b-d-doyle** [comment]
Awesome! Great library, it's made my life a lot easier. Thanks!
